apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: breastcancer-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: nazhahamdan7/backend-breastcancer:1.0
          ports:
            - containerPort: 8080

          envFrom:
            - configMapRef:
                name: backend-config

            - secretRef:
                name: backend-secret