apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: breastcancer-app
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: nazhahamdan7/frontend-breastcancer:1.0
          ports:
            - containerPort: 80
          readinessProbe:                 # <-- ICI, dans le même conteneur
            httpGet:
              path: /index.html
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:                  # <-- ICI aussi, juste après
            httpGet:
              path: /index.html
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 20